### ISSUE TITLE
Need help: code actions from multiple sources are not collated

### ISSUE THREAD

**Issue by ajitid** [williamboman/nvim-config#1]
Apologies for bothering you again. 

I noticed that in your setup code actions from tsserver and ESLint [appear in a single popup](https://github.com/nvim-telescope/telescope.nvim/issues/724#issue-849926995) and it looks like [in your config](https://github.com/williamboman/nvim-config/blob/main/lua/wb/telescope/lsp.lua#L6) Telescope code action is called as it is. I'm not able to understand why in my setup code actions for LSPs come one after the other and not simultaneously.

![ss](https://user-images.githubusercontent.com/26769888/114081114-051d7b80-9861-11eb-96c9-3a6139d4a2a5.gif)

Have you faced a similar problem? I'm new to Vim and am facing issues in setting up few things. Any help will be appreciated!

**Comment by williamboman** [comment]
So the telescope variant in your recording seem to be suffering from the bug where telescope only displays code actions from the very first language server. I've opened a fix for this (https://github.com/nvim-telescope/telescope.nvim/pull/722) which will likely be merged soon.

The other variant, where you're calling the builtin neovim LSP function, seems to simply dispatch the [textDocument/codeAction](https://github.com/neovim/neovim/blob/b518b9076f59f3e24e4afb5fb9468b1d5212b1b5/runtime/lua/vim/lsp/buf.lua#L364) request to all LSP servers connected to the current buffer. It does so without providing a handler, which results in the default [handler for textDocument/codeAction](https://github.com/neovim/neovim/blob/b518b9076f59f3e24e4afb5fb9468b1d5212b1b5/runtime/lua/vim/lsp/handlers.lua#L113) being executed. Since you have two LSP servers running (tsserver & eslint), that handler will be executed twice, i.e. you will be prompted twice.
